name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: esp-idf Toolchain Setup
      run: |
        sudo apt install gcc git wget make libncurses-dev flex bison gperf
        sudo apt install python3-pip python-is-python3
        wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-96-g2852398-5.2.0.tar.gz
        tar zxvf xtensa-esp32-elf-linux64-1.22.0-96-g2852398-5.2.0.tar.gz
    - name: Build
      run: |
        export PATH=$(pwd)/xtensa-esp32-elf/bin:${PATH}
        export IDF_PATH=$(pwd)/esp-idf
        pip3 install -r $IDF_PATH/requirements.txt
        make -j2
